FROM jaegertracing/jaeger-query:latest

FROM alpine
COPY --from=0 /go/bin/query-linux /go/bin/query-linux

ENV SPAN_STORAGE_TYPE grpc-plugin
ENV GRPC_STORAGE_PLUGIN_BINARY /go/bin/jaeger-influxdb-linux
ENV GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE /etc/jaeger/influxdb-plugin-config.yaml

COPY ./cmd/jaeger-influxdb/jaeger-influxdb-linux /go/bin/jaeger-influxdb-linux
COPY ./config-example-v1.yaml /etc/jaeger/influxdb-plugin-config.yaml

ENTRYPOINT /go/bin/query-linux
