FROM jaegertracing/all-in-one:latest

FROM alpine
COPY --from=0 /go/bin/all-in-one-linux /go/bin/all-in-one-linux

ENV SPAN_STORAGE_TYPE grpc-plugin
ENV GRPC_STORAGE_PLUGIN_BINARY /go/bin/jaeger-influxdb-linux
ENV GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE /etc/jaeger/influxdb-plugin-config.yaml

COPY ./cmd/jaeger-influxdb/jaeger-influxdb-linux /go/bin/jaeger-influxdb-linux
COPY ./config-example-v1.yaml /etc/jaeger/influxdb-plugin-config.yaml
